### ISSUE TITLE
build folder should not be excluded

### ISSUE THREAD

**Issue by saschahauke** [sbszcz/spring-conf-metadata-markdown-gradle-plugin#1]
Really like this plugin and the simplicity of it, but can't use it because the build folder is excluded because spring creates the json files there. Or am i missing something? An option to disable this exclusion would be nice

**Comment by sbszcz** [comment]
Hi Sascha, thanks for your feedback. The reason for this decision was that I use this plugin only inside a gradle-plugin project. Your objection is absolutely valid. I think I could make the exclusion folder(s) configurable.

**Comment by sbszcz** [comment]
Hi Sascha, please have a look at the readme file. There is an example how to control exclusion and how to disable it. I hope this helps.

**Comment by saschahauke** [comment]
Hi Sebastian, thanks for the quick update. I Could get it to work with `ignore.add("")` as `ignore.set([])` won't compile:

```
build.gradle.kts:264:12: Overload resolution ambiguity:
public abstract fun set(p0: (Mutable)Iterable<String!>?): Unit defined in org.gradle.api.provider.ListProperty
public abstract fun set(p0: Provider<out (Mutable)Iterable<String!>!>!): Unit defined in org.gradle.api.provider.ListProperty
```

im not really familiar with kotlin so i don't know if its on my end or if the parameter should be provided differently. The output though is amazing and it really helps me out a lot, thanks.

**Comment by sbszcz** [comment]
Hi Sascha, my fault. Thats a documentation mistake. I corrected that part. 

Kotlin
```kotlin
ignore.set(listOf(""))
```

Groovy
```groovy
ignore.set([""])

ignore = [""]
```
